volumes:
  static_files:
  esdata:
  sync_state:

services:
  x-app: &app
    build: app
    networks:
      - project_network
    restart: "unless-stopped"
    env_file:
      - .env
    environment:
      - ELASTIC_HOST=admin_elasticsearch
      - SQL_HOST=admin_postgres

  admin_nginx:
    image: nginx:1.26
    networks:
      - project_network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs/nginx:/etc/nginx/conf.d:ro
      - static_files:/data
    depends_on:
      - admin_service
    ports:
      - "81:80"
    restart: always

  admin_elasticsearch:
    image: elasticsearch:8.6.2
#    ports:
#      - "9200:9200"
    networks:
      - project_network
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - /home/maria/ES_dumps:/usr/share/elasticsearch/snapshots
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "path.repo=/usr/share/elasticsearch/snapshots"
    restart: always

  admin_postgres:
    image: postgres:16
    ports:
      - "30000:30000"
    networks:
      - project_network
    env_file:
      - postgres.env
    command:
      ["postgres", "-c", "log_statement=all"]
    restart: always

  admin_swagger:
    image: swaggerapi/swagger-ui:v5.17.14
    networks:
      - project_network
    volumes:
      - ./openapi.yaml:/swagger.yaml
    ports:
      - "8080:8080"
    environment:
      SWAGGER_JSON: /swagger.yaml
      BASE_URL: "/swagger/"
    restart: always

  admin_service:
    <<: [*app]
    volumes:
      - static_files:/opt/app/static
    expose:
      - "8000"
    command: ["uwsgi", "--strict", "--ini", "uwsgi.ini"]

  admin_django-migrations:
    <<: [*app]
    container_name: "admin_django-migrations"
    restart: "no"
    command: [ "python", "manage.py", "migrate" ]
    depends_on:
      - admin_postgres

  admin_postgres_to_es:
    <<: [*app]
    volumes:
      - sync_state:/opt/app/state
    command: [ "python", "manage.py", "postgres_to_es" ]
    restart: always

networks:
  project_network:
    external: true